# Data base
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/products
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

# API
api:
  limit:
    login:
      attempt: 3
      timeout:
        lock: 30
    resources:
       access: 1000000
       timeout:
         lock: 1440
